use world;
show databases;
show tables;
select * from  city;
describe city;
select * from country;
describe country;
select * from countrylanguage;
describe countrylanguage;
use sys;
show tables;
select * from host_summary_by_stages;
